### PR TITLE
Use Plug.Builder insted of Plug behaviour (compatible with recent ver…

### PR DESCRIPTION
**Pull request by jeanparpaillon**
…sions of Plug)

### CODE REVIEW

**Comment by michalmuskala** [comment]
What's the benefit of doing this?

**Comment by jeanparpaillon** [comment]
First, sorry for the noise in the commit, my code formatter :/ 

Without `use Plug.Builder`, it does not compile because of missing `halt` function. I have not checked deeply but I suppose `use Plug.Builder` imports some functions

**Comment by jeanparpaillon** [comment]
ping

**Comment by michalmuskala** [comment]
Ah, this is fixed by using the fully qualified names e.g. `Plug.Conn.halt()` instead of just `halt()`. Fixed in master, a release will follow soon.

**Comment by jeanparpaillon** [comment]
Got it, thanks !

**Pull request closed without merging**
